export default [
  {word: "Machaya", hint:"To do something great"},
  {word: "Makhaya", hint:"To do a task poorly"},
  {word: "Insti Top", hint:"Highest point of KGP"},
  {word: "Gol C", hint:"Here stands BC Roy"},
  {word: "Bhaat", hint:"A local meetup"},
  {word: "Maggu", hint:"A special kind of species with just one goal"},
  {word: "Rassa", hint:"They often conduct strikes in campus :P"},
  {word: "Matka", hint:"Not a UG, not a scholar"},
  {word: "Dassi", hint:"Academic gods"},
  {word: "Peace", hint:"The most famous one"},
  {word: "Illumination", hint:"Lights."},
  {word: "Happa", hint:"Hall president"},
  {word: "Tempo Shout", hint:"We don't scream we have  ____"},
  {word: "Chaggi", hint:"Probably the most common CG"},
  {word: "Panji", hint:"He is a dude"},
  {word: "Faccha", hint:"The noobs of KGP"},
  {word: "Frustapa", hint:"Anxiety and annoyance for a KGPian"},
  {word: "Bhajan", hint:"60% of DC searches"},
  {word: "Funda", hint:"the basic principle behind something"},
  {word: "Geez", hint:"eating someone's stuff as of its own"},
  {word: "Load", hint:"To Have Tension"},
  {word: "Fakka", hint:"An F-grade in any subject"},
  {word: "Lodu", hint:"A person who takes lot of load"},
  {word: "Banda", hint:"Any Boy"},
  {word: "Bhaatu", hint:"A person who is very talkative"},
  {word: "Archi", hint:"The Architecture Department"},
  {word: "Taapna", hint:" Copying assignments or examination answer-scripts from any person"},
  {word: "Makhana", hint:"To spoil a job"},
  {word: "Stud", hint:"Any student who is good in academics as well as other fields like sports"},
  {word: "Bandi", hint:"Any girl"},
  {word: "Batti", hint:"The Electrical Engineering Department"},
  {word: "Hathora", hint:"The Mechanical Engineering Department"},
  {word: "Junta", hint:"The human population"},
  {word: "Chhedis", hint:"A dhaba just outside campus"},
  {word: "Atthi", hint:"A C.G.P.A. in between 8 and 9"},
  {word: "Nehli", hint:"A C.G.P.A. greater than 9"},
  {word: "Panji", hint:"A C.G.P.A. in between 5 and 6"},
  {word: "Bhaat", hint:"Bekar Chat"},
  {word: "Ghaasi", hint:"A student of Agriculture Engineering Department"},
];
